---
- name: copy createUsers script
  template: src=createUsers.j2 dest=/tmp/createUsers.js

- name: create users
  shell: mongo --ssl --sslAllowInvalidCertificates --host "{{ groups['primary'][0] }}" < /tmp/createUsers.js
